### ISSUE TITLE
App Will Not "Gulp Serve", same issue for two operating systems.

### ISSUE THREAD

**Issue by MattA9K** [johnpapa/ng-demos#103]
After 
`npm install`
`npm install gulp`

I'll get this:

**macOS Mojave**

```
Matts-MacBook-Pro:modular mattmbp$ gulp serve

/Users/mattmbp/Downloads/ng-demos-master/modular/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/mattmbp/Downloads/ng-demos-master/modular/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mattmbp/Downloads/ng-demos-master/modular/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)`

```

**Linux Mint v18 64-bit**
```
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/mint/Desktop/ng-demos-master/modular/node_modules/karma/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mint/Desktop/ng-demos-master/modular/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:652:30)
```

Not sure what the issue is about.

**Comment by samjulien** [comment]
Howdy -- this can be corrected by updating Karma in `package.json` (I used the current version) and running `npm install` again. Cheers!
