### ISSUE TITLE
Error while 'npm install' for modular

### ISSUE THREAD

**Issue by Aman-US-Punjabi** [johnpapa/ng-demos#30]
I tried to run npm install but shows me error : -

EEXIST, open '/Users/Username/.npm/10afb59f-adable-stream-1-0-33-package-tgz.lock'
File exists: /Users/Username/.npm/10afb59f-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

I tried it few times , but face same error and if i try to run gulp serve-dev , i face error :- 

Error: Cannot find module 'source-map'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/AngularCleanCode/modular/node_modules/karma/lib/reporter.js:5:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by m2web** [comment]
I was having the same issue and did the following
> npm install source-map&&gulp-less
and all was well then.
