### ISSUE TITLE
Error on gulp serve-dev

### ISSUE THREAD

**Issue by mradul** [johnpapa/ng-demos#60]
I was trying to follow this tutorial and am getting the following error  when I run the command 'gulp serve-dev'-

C:\Users\mradul.jain\play\ng-demos\modular [master]> gulp serve-dev
[09:10:14] Using gulpfile ~\play\ng-demos\modular\gulpfile.js
[09:10:14] Starting 'serve-dev'...
[09:10:15] Finished 'serve-dev' after 293 ms
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: C:\Users\mradul.jain\play\ng-demos\modular\src\server
/**/*
[gulp] [nodemon] starting `node ./src/server/app.js`
events.js:85
**      throw er; // Unhandled 'error' event**
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

PS - I have no experience in node.js/bower so parodon me if I am missing something very basic.

**Comment by enterpriseSoftware** [comment]
I was able to get around this issue by npm install -g inflight

Someone let me know if this was the right thing to do.

**Comment by francisrod01** [comment]
@mradul this is solved?
