### ISSUE TITLE
Error in runtime cc-bmean: process.nextTick TypeError Trailer name must be a valid HTTP Token Content ["Content-Type:"]

### ISSUE THREAD

**Issue by MarkoKacprzak** [johnpapa/ng-demos#84]
During runing that sample i've receive an error:

ng-demos\cc-bmean\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Trailer name must be a valid HTTP Token ["Content-Type:"]
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at sendResults (c:\Git\ng-demos\cc-bmean\src\server\routes\index.js:208:13)
    at c:\Git\ng-demos\cc-bmean\src\server\routes\index.js:169:17
    at c:\Git\ng-demos\cc-bmean\src\server\routes\index.js:86:21
    at handleCallback (c:\Git\ng-demos\cc-bmean\node_modules\mongodb\lib\utils.js:96:12)
    at c:\Git\ng-demos\cc-bmean\node_modules\mongodb\lib\cursor.js:835:16
    at handleCallback (c:\Git\ng-demos\cc-bmean\node_modules\mongodb-core\lib\cursor.js:159:5)
    at setCursorDeadAndNotified (c:\Git\ng-demos\cc-bmean\node_modules\mongodb-core\lib\cursor.js:480:3)
    at nextFunction (c:\Git\ng-demos\cc-bmean\node_modules\mongodb-core\lib\cursor.js:631:7)
    at Cursor.next [as _next] (c:\Git\ng-demos\cc-bmean\node_modules\mongodb-core\lib\cursor.js:672:3)

You could fix it by changing file
cc-bmean\src\server\routes\index.js

function sendResults(res, results) {
...................
        res.setHeader('Content-Type:', 'application/json');
...................
    }

Should be:
function sendResults(res, results) {
...................
        res.setHeader('Content-Type', 'application/json');
...................
    }

similar problem found at Breeze samples issues:
https://github.com/Breeze/breeze.js.samples/issues/36

**Comment by Salakawy** [comment]
res.setHeader('Content-Type:', 'application/json'); should be res.setHeader('Content-Type', 'application/json');
