### ISSUE TITLE
Issues with running the npm serve-dev

### ISSUE THREAD

**Issue by bsricharan** [johnpapa/ng-demos#87]
I did try git clone https://github.com/johnpapa/ng-demos.git and it did not bring the ng-demos-modular folder . is that required ?

After that when i tried gulp serve dev
a)cannot find module active-x-obfuscator

![image](https://cloud.githubusercontent.com/assets/16442396/14682353/40bdb1c8-06f3-11e6-9ba4-e19e79e1f05e.png)

b) in order to correct that i tried npm install active-x-obfuscator, i get below error.
![image](https://cloud.githubusercontent.com/assets/16442396/14682468/b9db55ba-06f3-11e6-8df3-f0d65ea43119.png)

some of the blogs i read said that did your NPM install went as expected ?
i do not see errors but i saw warning as if it so many modules depreciated .

Please help what i need to do to load the ng-demos project

**Comment by demonno** [comment]
I had a problem `gulp serve-dev` was not working 
reason was version of `node` and `karma`

> /Users/dn/workspace/ngwork/ng-demos/modular/node_modules/karma/node_modules/socket.io/lib/store.js:35
> Store.prototype.__proto__ = EventEmitter.prototype;
>                                         ^
> 
> TypeError: Cannot read property 'prototype' of undefined
>     at Object.<anonymous> (/.../ng-demos/modular/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (.../ng-demos/modular/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
>     at Module._compile (module.js:573:32)


Fixed it by upgrading `karma` on latest `1.3.0`and `node` on latest `v7.1.0`.
